default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: tjstockoptima_production
  username: <%= ENV['PG_USERNAME'] %> # or hardcode your PostgreSQL username
  password: <%= ENV['PG_PASSWORD'] %> # or hardcode your password if needed
  host: localhost
  port: 5432
