test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
production:
  backblaze:
    service: S3
    access_key_id: <%= Rails.application.credentials.dig(:backblaze, :b2, :key_id) %>
    secret_access_key: <%= Rails.application.credentials.dig(:backblaze, :b2, :application_key) %>
    region: us-east-005
    bucket: 14cc8f9ae6cd380890380211
    endpoint: https://s3.us-east-005.backblazeb2.com


