
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
production:
  backblaze:
    service: Backblaze
    bucket: <%= ENV["BACKBLAZE_BUCKET_NAME"] %>
    key_id: <%= ENV["BACKBLAZE_ACCESS_KEY_ID"] %>
    application_key: <%= ENV["BACKBLAZE_SECRET_ACCESS_KEY"] %>

